.PHONY: clean All

All:
	@echo "----------Building project:[ section10Challenge - Debug ]----------"
	@cd "section10Challenge" && "$(MAKE)" -f  "section10Challenge.mk"
clean:
	@echo "----------Cleaning project:[ section10Challenge - Debug ]----------"
	@cd "section10Challenge" && "$(MAKE)" -f  "section10Challenge.mk" clean
