.PHONY: clean All

All:
	@echo "----------Building project:[ codingExercise20 - Debug ]----------"
	@cd "codingExercise20" && "$(MAKE)" -f  "codingExercise20.mk"
clean:
	@echo "----------Cleaning project:[ codingExercise20 - Debug ]----------"
	@cd "codingExercise20" && "$(MAKE)" -f  "codingExercise20.mk" clean
