.PHONY: clean All

All:
	@echo "----------Building project:[ AccessModifiersSettersGetters - Debug ]----------"
	@cd "AccessModifiersSettersGetters" && "$(MAKE)" -f  "AccessModifiersSettersGetters.mk"
clean:
	@echo "----------Cleaning project:[ AccessModifiersSettersGetters - Debug ]----------"
	@cd "AccessModifiersSettersGetters" && "$(MAKE)" -f  "AccessModifiersSettersGetters.mk" clean
